---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[curl]
  - recipe[curl::dev]
  attributes:
- name: gnutls
  run_list:
  - recipe[curl]
  - recipe[curl::dev]
  attributes:
    libcurl:
      variant: gnutls
- name: nss
  run_list:
  - recipe[curl]
  - recipe[curl::dev]
  attributes:
    libcurl:
      variant: nss
